apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-clusterrole-binding
subjects:
- kind: ServiceAccount
  name: final-service
  namespace: default
roleRef:
  kind: ClusterRole
  name: final-cluster-role
  apiGroup: rbac.authorization.k8s.io