apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: final-binding
  namespace: default
roleRef: # points to the Role
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: final-role # name of Role
subjects: # points to the ServiceAccount
- kind: ServiceAccount
  name: final-service # service account to bind to
  namespace: default # ns of service account


apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-bind-kubes
  namespace: kube-system
roleRef: # points to the Role
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: roles-kubes # name of Role
subjects: # points to the ServiceAccount
- kind: ServiceAccount
  name: final-service # service account to bind to
  namespace: kube-system # ns of service account