name: Setup Prefect-Kubernetes
run-name: Setup Prefect-Kubernetes
on: [push]
jobs:
  upload-script-kubernetes:
    runs-on: ubuntu-latest
    container: prefecthq/prefect:2.8.2-python3.9
    env:
      KEY: ${{secrets.PREFECT_API_KEY}}
      REP_URL: ${{vars.REP_URL}}
      ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
    steps:
      - uses: actions/checkout@v4
      - run: pip install -r requirements.txt
      - run:   prefect cloud login --key $KEY --workspace noahskusabagmailcom/noah-github
      - name: Create Prefect Infastructure & Storage Blocks 
        run: python k8_infra_setup.py 
      - name: Deply to prefect
        run: prefect deployment build main.py:main --cron "0 8 * * *" --timezone="America/New_York"  -n noahKubernetes -p default-agent-pool -sb github/etl-kubernetes -ib kubernetes-job/k8s-flow -a
