name: Setup Prefect-Kubernetes
run-name: Setup Prefect-Kubernetes
on: [push]
jobs:
  upload-script-kubernetes:
    runs-on: ubuntu-latest
    container: 
    env:
      KEY: ${{secrets.PREFECT_API_KEY}}
      REP_URL: ${{vars.REP_URL}}
    steps:
      - uses: actions/checkout@v4
      - run: pip install -r requirements.txt
      - run:   prefect cloud login --key $KEY --workspace noahskusabagmailcom/noah-github
      - name: Create Prefect Infastructure & Storage Blocks 
        run: python k8_infra_setup.py 
      - name: Deply to prefect
        run: prefect deployment build main.py:main -n noahKubernetes -p default-agent-pool -sb github/ETL_Pipeline_Kubernetes -ib kubernetes-job/k8-sflow -a
        # --workspace noah-github 