name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  upload-script-kubernetes:
    runs-on: ubuntu-latest
    container: 
    env:
      KEY: ${{ secrets.PREFECT_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - run: pip install -r requirements.txt
      - run:  prefect cloud login --key  $Key 
      - name: Create Prefect Infastructure & Storage Blocks 
        run: python k8_infra_setup.py 
      - name: Deply to prefect
        run: prefect deployment build main.py:main -n noahKubernetes -p default-agent-pool -sb github/ETL_Pipeline_Kubernetes -ib kubernetes-job/k8-sflow -a
